version: "3.8"

services:
  tailbrain:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tailbrain
    ports:
      - "7654:7654"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=7654
      - HOST_RELAY_URL=http://host.docker.internal:7655
    extra_hosts:
      - "host.docker.internal:host-gateway"
